from models.llama import CustomLlamaForCausalLM
from models.llama_layer import CustomLlamaForCausalLM as ClusterLayerLlamaForCausalLM
from models.mistral_layer import CustomMistralForCausalLM as ClusterLayerMistralForCausalLM